name: fibonacci_list
description: >-
  Proyecto Dart que genera una lista de números pertenecientes a la sucesión de Fibonacci.
version: 1.0.0
publish_to: 'none'
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies: {}
dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
